anafi:
  pid_controller:
    ros__parameters:
      gains:  # Controller gains
        position:  # Position gains
          p: 2.0  # Position proportional gain
          i: 1.0  # Position integral gain
          d: 0.5  # Position derivative gain
          max_i: 0.1  # Position max integral component
        velocity:  # Velocity gains
          p: 9.1  # Velocity proportional gain
          d: 1.3  # Velocity derivative gain
        yaw:  # Yaw gains
          p: 70.0  # Yaw proportional gain

