/**:
  ros__parameters:
    armed: false
    hand_launch: false
    landing_control: false
    takingoff_control: false
    mission_type: 0
    start_type_description_service: true
    use_sim_time: false
    fixed_frame: false
    world_frame: false
    follow_me/mode: 2

    # Bounds
    bounds/x/max: 10.0
    bounds/x/min: -10.0
    bounds/y/max: 10.0
    bounds/y/min: -10.0
    bounds/z/max: 2.0 #binded to anafi/drone/max_altitude
    bounds/z/min: 0.0

  
    # QoS Settings
    qos_overrides:
      /parameter_events:
        publisher:
          depth: 1000
          durability: volatile
          history: keep_last
          reliability: reliable