/**:
  ros__parameters:
    # Position Gains
    gains/position/d: 0.5
    gains/position/i: 2.0
    gains/position/max_i: 0.1
    gains/position/p: 2.0

    # Velocity Gains
    gains/velocity/d: 3.0
    gains/velocity/i: 1.0
    gains/velocity/max_i: 0.5
    gains/velocity/p: 20.0

    # Yaw Gains
    gains/yaw/p: 70.0